### ISSUE TITLE
Wildcard for function whitelist option

### ISSUE THREAD

**Issue by tommy-muehle** [QafooLabs/php-profiler-extension#7]
Hi,

thanks for providing this extension and the new options against xhprof!

But i have one question. Its possible to set / implement a wildcard for the whitelist function filter?
So something like this

     qafooprofiler_enable(0, array(
         'functions' => array('Foo\Bar::*')
     ));
 
for all methods in class Foo\Bar
or 

     qafooprofiler_enable(0, array(
        'functions' => array('Foo\*')
     ));

for all classes under Foo inclusive methods?

**Comment by beberlei** [comment]
@tommy-muehle That is not possible right now, because the way whitelisting works. It implements its own hashmap on C level and checks for the equivalent of `isset($functions['Foo\Bar::baz']);` - This is necessary for performance reasons, otherwise we would need to perform a regexp on every function call.
